export interface Broker {
  name: string;
  country: string;
  regulation: string[];
  type: ('crypto' | 'stock' | 'forex' | 'derivatives' | 'broker')[];
  fees: string;
  minDeposit: string;
  pros: string[];
  cons: string[];
  apiAvailable: boolean;
  url: string;
  rating: number;
}

export const BROKERS: Broker[] = [
  {
    name: 'Interactive Brokers',
    country: 'USA',
    regulation: ['SEC', 'FINRA', 'AMF', 'FCA'],
    type: ['stock', 'forex', 'derivatives'],
    fees: 'Tres bas (~0.005 $/action min 1$)',
    minDeposit: '0 $',
    pros: [
      'Plus de 150 marches mondiaux.',
      'API IBKR robuste, librairies officielles.',
      'Spread serre, marge competitive.',
    ],
    cons: ['Interface dense pour debutants.', 'Conversion forex requise.'],
    apiAvailable: true,
    url: 'https://www.interactivebrokers.com',
    rating: 4.7,
  },
  {
    name: 'Saxo Bank',
    country: 'Danemark',
    regulation: ['DFSA', 'FCA', 'AMF'],
    type: ['stock', 'forex', 'derivatives'],
    fees: 'Variable selon le profil (entry / classic / platinum)',
    minDeposit: '0 € (compte classique)',
    pros: ['Plateforme premium SaxoTraderGO.', 'Recherche de qualite.', 'API REST disponible.'],
    cons: ['Frais plus eleves sur les petits comptes.'],
    apiAvailable: true,
    url: 'https://www.home.saxo',
    rating: 4.4,
  },
  {
    name: 'Trade Republic',
    country: 'Allemagne',
    regulation: ['BaFin', 'AMF'],
    type: ['stock'],
    fees: '1 € par ordre',
    minDeposit: '0 €',
    pros: ['Frais ultra-bas.', 'Mobile-first soigne.', 'Compte remunere.'],
    cons: ['Pas d\'API publique.', 'Moins de produits avances.'],
    apiAvailable: false,
    url: 'https://traderepublic.com',
    rating: 4.3,
  },
  {
    name: 'eToro',
    country: 'Israel / UK',
    regulation: ['CySEC', 'FCA', 'AMF'],
    type: ['stock', 'forex', 'crypto'],
    fees: 'Spread, retrait 5$, conversion EUR/USD',
    minDeposit: '50 $',
    pros: ['Copy-trading social.', 'Crypto + actions + ETF unifies.'],
    cons: ['Spreads larges.', 'Pas le moins cher.'],
    apiAvailable: false,
    url: 'https://www.etoro.com',
    rating: 4.0,
  },
  {
    name: 'Binance',
    country: 'International',
    regulation: ['PSAN AMF (FR)', 'MAS', 'DASP'],
    type: ['crypto', 'derivatives'],
    fees: '0.1% spot, 0.04% futures (BNB discount)',
    minDeposit: '10 $',
    pros: ['Liquidite #1 mondial.', 'API complete REST + websocket.', 'Catalogue immense.'],
    cons: ['Pression reglementaire dans plusieurs pays.', 'Interface complexe au debut.'],
    apiAvailable: true,
    url: 'https://www.binance.com',
    rating: 4.5,
  },
  {
    name: 'Coinbase',
    country: 'USA',
    regulation: ['NYDFS', 'SEC (cote en bourse)'],
    type: ['crypto'],
    fees: 'Spread + frais variables. Coinbase Advanced ~0.6%',
    minDeposit: '0 $',
    pros: ['Tres regule, on-ramp simple.', 'Disponible US + EU.', 'API publique.'],
    cons: ['Frais standard eleves.', 'Moins de paires que Binance.'],
    apiAvailable: true,
    url: 'https://www.coinbase.com',
    rating: 4.2,
  },
  {
    name: 'Kraken',
    country: 'USA',
    regulation: ['FinCEN', 'FCA'],
    type: ['crypto', 'derivatives'],
    fees: '0.16% maker / 0.26% taker',
    minDeposit: '10 $',
    pros: ['Securite historique.', 'Bonne pour staking.', 'API solide.'],
    cons: ['Plateforme moins moderne que Binance.'],
    apiAvailable: true,
    url: 'https://www.kraken.com',
    rating: 4.3,
  },
  {
    name: 'Alpaca',
    country: 'USA',
    regulation: ['FINRA', 'SIPC'],
    type: ['stock', 'crypto'],
    fees: 'Commission 0$',
    minDeposit: '0 $',
    pros: ['API-first (parfait pour bots).', 'Paper trading natif.', 'Documentation excellente.'],
    cons: ['US only pour le compte live.'],
    apiAvailable: true,
    url: 'https://alpaca.markets',
    rating: 4.6,
  },
  {
    name: 'Bitget',
    country: 'Seychelles',
    regulation: ['DASP'],
    type: ['crypto', 'derivatives'],
    fees: '0.1% spot, 0.06% futures',
    minDeposit: '10 $',
    pros: ['Leader copy-trading crypto.', 'Bons bots integres.'],
    cons: ['Moins regule en EU.'],
    apiAvailable: true,
    url: 'https://www.bitget.com',
    rating: 4.0,
  },
  {
    name: 'Bourse Direct',
    country: 'France',
    regulation: ['AMF', 'ACPR'],
    type: ['stock', 'broker'],
    fees: 'Forfaits a partir de 0.99 € (Euronext)',
    minDeposit: '0 €',
    pros: ['PEA / PEA-PME / Assurance vie.', 'Pure-player FR.'],
    cons: ['Pas d\'API publique.'],
    apiAvailable: false,
    url: 'https://www.boursedirect.fr',
    rating: 3.9,
  },
];
